utilPath=C:\\Users\\aditya.verma\\rocps_web_automation_master\\rocps_web_automation\\roc-automation-util
downloadDirectory=C:\\Users\\aditya.verma\\Downloads
browser=firefox
recordExecution=Yes
embedImageInReport=Yes
product=ROCPS

# Deployment Details
clientUrl=http://10.113.145.147:8080/42_entrypoint-10.5.57.0
deployPath=/home/subexuser/Automation_Setup/rocps-server-distribution-10.5.57.0
tomcatPath=/home/subexuser/Automation_Setup/tomcat
dateFormat=yyyy-MM-dd
timeFormat=
os=Windows
machineName=10.113.145.147
taskControllerExeFile=tc.bat
taskControllerName=Task Controller

#Path Details
dataDir=/home/subexuser/Automation_Setup/DataDir
cdrPath=\\src\\main\\resources\\Data\\FunctionalTesting\\CDRS\\
ratesheetPath=\\src\\main\\resources\\Data\\FunctionalTesting\\RateSheet\\
java11Path=C:Program FilesJavajdk-11.0.30

#Bulk loader Path Details
bulkLoadStreamPath=\\src\\main\\resources\\Data\\FunctionalTesting\\BulkLoadStream\\
bulkExportPath=BulkDataExportConfiguration\\

#Carrier Invoice Path Details
carrierInvoiecPath=\\src\\main\\resources\\Data\\FunctionalTesting\\CarrierInvoice\\

#XDR Path Details
xdrExtFullPath=XDRExtraction\\XDRExtractionFull\\
xdrExtFullPath2=XDRExtraction\\XDRExtractionFullWithBill\\

#Roaming Path Details
roamingFilePath=\\src\\main\\resources\\Data\\FunctionalTesting\\RoamingFilePath\\
roamingRapOutFilePath=Roaming\\RapOut\\
roamingTapOutFilePath=Roaming\\TapOut\\

#Reports and Extracts Path Details
repExtFlLocAdhocPath=ExtractFlLocation\\adhoc\\
repExtFlLocSchedulePath=ExtractFlLocation\\scheduled\\
repExtGenBirtRepTargetPath=GenBirtReport\\Target\\

#Event Usage Request Path Details
rocpsExpAllRowsPath=ROCPSExportAllRows\\

#File Upload Path Details
#fileUploadFiles=\\src\\main\\resources\\Data\\FunctionalTesting\\FileUpload\\
fileUploadFiles=\\src\\main\\resources\\Birt\\

#PDF Excle Template Path Details
pdfToExcelFiles=\\src\\main\\resources\\Data\\FunctionalTesting\\PdfToExcel\\
pdfConversionFolder=PdfToExcel

#Deal Import Path Details
dealImport=\\src\\main\\resources\\Data\\FunctionalTesting\\DealImport\\
dealImportTemplateFolder=DealImportExcelWriter\\
dealImportTempalteBackup=DealImportBackup\\

#Sikulli Image Name xpath

fileTypeUploadImageName=fileTypeFU6.PNG
openButtoneUploadImageName=openButtonFU6.PNG

## Linux Details
#remoteHostname=<Remote Host IP>
#remoteUsername=<Remote Host Username>
#remotePassword=<Remote Host Password>
#remotePortNumber=22

# Application Details
applicationName=ROC Partner Settlement
applicationUsername=Root
applicationPassword=Welcome@777
clientPartitionFlag=N
partition=Common

# Reference Database Details
dbType=PostgreSQL
dbMachineName=10.113.145.147
dbInstance=Ref DB
database=rocps_ref_automation
dbUserName=rocps_ref_automation
dbPassword=rocps_ref_automation
dbPortNumber=5433
dbUnicode=N
dbLinkToReferenceDB=
dbLinkToStagingDB=
dbLinkToUsageServer=
dbMaxActiveConnections=
dbMaxIdleConnections=
dbMinIdleConnections=
dbExhaustedAction=
dbONSConfig=

# Performance Properties
calculatePerformance=No

# Usage Database Details
usageDBType=PostgreSQL
usageMachineName=10.113.145.147
usageInstance=rocps_automation_usg
usageDatabase=rocps_automation_usg
usageUsername=rocps_automation_usg
usagePassword=rocps_automation_usg
usagePortNumber=5432
usageUnicode=N
usageSecondaryMachines=
usageLinkToReferenceDB=
usageLinkToStagingDB=
usageLinkToUsageServer=
usageMaxActiveConnections=
usageMaxIdleConnections=
usageMinIdleConnections=
usageExhaustedAction=
usageONSConfig=

# PostgreSQL Properties (Required if database is PostgreSQL)
postgreSQLRestoreExeFile=

# Data Generation Properties
dataDateFormat=ddMMyyyy_HHmm

# Now Date Related Properties
dateTimeFormat=ddMMyyyy_HHmmss
currentNowDateTime=
previousNowDateTime=

# Mail Details (Required if Mail Notification has to be sent)
sendMail=No
mailSendingUserName=Rahul Muraleedharan
mailToAddress=rahul.muraleedharan@subex.com
mailCCAddress=rahul.muraleedharan@subex.com

# Performance Properties
searchScreenWaitSec=150
detailScreenWaitSec=30
searchTryCount=3
expectedTries=3

# Automation Properties
firstLevelDelimiter=|
secondLevelDelimiter=;
thirdLevelDelimiter=!

startTomcat=No
clientStartWaitTimeMins=60
clientPreviousBuildNo=76
serverPreviousBuildNo=37
lastReportDate=06/14/2017 14:43:04
automationSVNPath=<svn Path>

# Script Properties (User created properties)
WaitSecs=2
UsageGroupWaitTimeInSecs=300
EntityImportWaitInSecs=300
DataPath=D:\\selenium\\Automation\\Latest\\Data

#Partner Settlement  Properties
SearchLoopTimeLimitInSecs =20
partitionerrorusagegroup=NewUsageGroup
baselinedTestCases=1500
automatedTestCases=1200
